### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kliegl**

### CODE REVIEW

**Review by dmbates — CHANGES_REQUESTED** [review]
Would you be willing to make this change in README.jmd instead of README.md?  The idea is that README.jmd is the original source and README.md is the derived file.

In this case it is rather trivial but it is a good habit to keep clear which files are derived from others.  Most of the time the derived files would not be part of the repository but the name README.md is part of the github configuration.

**Comment by dmbates** [comment]
I should have said "in addition to".  The idea is that you make the changes to `README.jmd` then run the `weave` call then commit the changes to both files.  I can do it if you wish.

**Comment by kliegl** [comment]
Probably best if you do it. Perhaps also add an example for Pkg.add()?

**Comment by dmbates** [comment]
It turns out that it doesn't work terribly well to use `Pkg.add()` in a Weave document.  It outputs some control characters as part of showing download progress and that just creates a mess in the Markdown file.

**Comment by kliegl** [comment]
Ah yes. I only use it in the REPL and actually switch into the package mode to do it. Never mind.

**Comment by dmbates** [comment]
Superceded by commit #3dba18e

**Pull request closed without merging**
